import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link } from '@inertiajs/react';

type Batch = { id: number; status: string; delivered_at?: string | null; total_pre_sales: number; total_amount: number; branch?: { name: string }; zone?: { name: string }; delivered_by?: { name: string } | null };
type Props = { batches: { data: Batch[]; links: Array<{ url: string | null; label: string; active: boolean }> }; can_view_cash_settlements?: boolean };

export default function Index({ batches, can_view_cash_settlements = false }: Props) {
    return <AuthenticatedLayout><Head title="Lotes de ventas de ruta" /><div className="mx-auto max-w-6xl space-y-5 px-4 py-6 sm:px-6">
        <div><Link href={route('routes.work-days.closed')} className="text-sm font-semibold text-indigo-600">Jornadas</Link><div className="mt-2 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-semibold text-slate-950">Lotes de ventas de ruta</h1><p className="mt-1 text-sm text-slate-500">Ventas generadas desde preventas y seguimiento de su procesamiento, entrega y cobro.</p></div>{can_view_cash_settlements && <Link href={route('routes.cash-settlements.index')} className="rounded-lg border border-indigo-200 bg-indigo-50 px-3 py-2 text-sm font-semibold text-indigo-700">Liquidaciones de efectivo</Link>}</div></div>
        <div className="overflow-x-auto rounded-lg border border-slate-200 bg-white"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Lote</th><th className="px-4 py-3">Estado</th><th className="px-4 py-3">Generado</th><th className="px-4 py-3">Generado por</th><th className="px-4 py-3">Sucursal</th><th className="px-4 py-3">Zona</th><th className="px-4 py-3">Preventas</th><th className="px-4 py-3">Total</th><th className="px-4 py-3" /></tr></thead><tbody>{batches.data.map((batch) => <tr key={batch.id} className="border-t border-slate-100"><td className="px-4 py-3 font-semibold">#{batch.id}</td><td className="px-4 py-3">{batch.status === 'completed' ? 'Completada' : batch.status}</td><td className="px-4 py-3">{batch.delivered_at ? new Date(batch.delivered_at).toLocaleString() : '-'}</td><td className="px-4 py-3">{batch.delivered_by?.name ?? '-'}</td><td className="px-4 py-3">{batch.branch?.name ?? '-'}</td><td className="px-4 py-3">{batch.zone?.name ?? '-'}</td><td className="px-4 py-3">{batch.total_pre_sales}</td><td className="px-4 py-3">Q {Number(batch.total_amount).toFixed(2)}</td><td className="px-4 py-3"><Link className="text-sm font-semibold text-indigo-600" href={route('routes.delivery-batches.show', batch.id)}>Ver detalle</Link></td></tr>)}</tbody></table></div>
    </div></AuthenticatedLayout>;
}
