import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link } from '@inertiajs/react';

type Entry = { id: number; payment_method?: string | null; fel_dispatch_status?: string | null; error_message?: string | null; pre_sale?: { id: number; fel_eligibility_status?: string | null; fel_eligibility_reason?: string | null; customer?: { name: string; commercial_name?: string | null } }; sale?: { id: number; business_number?: number | null; total: number; certification_status?: string | null } };
type Batch = { id: number; total_amount: number; total_pre_sales: number; delivered_at?: string | null; delivered_by?: { name: string } | null; branch?: { name: string } | null; zone?: { name: string } | null; pre_sales: Entry[] };

export default function Show({ batch }: { batch: Batch }) {
    return <AuthenticatedLayout><Head title={`Entrega #${batch.id}`} /><div className="mx-auto max-w-6xl space-y-5 px-4 py-6 sm:px-6"><div><Link href={route('routes.delivery-batches.index')} className="text-sm font-semibold text-indigo-600">Entregas</Link><h1 className="mt-2 text-2xl font-semibold text-slate-950">Entrega #{batch.id}</h1><p className="text-sm text-slate-500">{batch.total_pre_sales} preventas · Q {Number(batch.total_amount).toFixed(2)}</p><dl className="mt-3 grid gap-2 text-sm text-slate-600 sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-xs font-semibold uppercase text-slate-500">Entregado por</dt><dd>{batch.delivered_by?.name ?? '-'}</dd></div><div><dt className="text-xs font-semibold uppercase text-slate-500">Fecha y hora</dt><dd>{batch.delivered_at ? new Date(batch.delivered_at).toLocaleString() : '-'}</dd></div><div><dt className="text-xs font-semibold uppercase text-slate-500">Sucursal</dt><dd>{batch.branch?.name ?? '-'}</dd></div><div><dt className="text-xs font-semibold uppercase text-slate-500">Zona</dt><dd>{batch.zone?.name ?? '-'}</dd></div></dl></div><div className="overflow-x-auto rounded-lg border border-slate-200 bg-white"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Cliente</th><th className="px-4 py-3">Forma de pago</th><th className="px-4 py-3">Comprobante</th><th className="px-4 py-3">FEL</th><th className="px-4 py-3">Elegibilidad FEL</th></tr></thead><tbody>{batch.pre_sales.map((entry) => <tr className="border-t border-slate-100" key={entry.id}><td className="px-4 py-3">{entry.pre_sale?.customer?.commercial_name || entry.pre_sale?.customer?.name || '-'}</td><td className="px-4 py-3">{paymentMethodLabel(entry.payment_method)}</td><td className="px-4 py-3">{entry.sale ? <Link className="font-semibold text-indigo-600" href={route('sales.show', entry.sale.id)}>#{entry.sale.business_number ?? entry.sale.id}</Link> : '-'}</td><td className="px-4 py-3"><div>{felLabel(entry.sale?.certification_status ?? entry.fel_dispatch_status)}</div>{entry.error_message && <div className="mt-1 max-w-xs text-xs text-amber-700">{entry.error_message}</div>}</td><td className="px-4 py-3">{entry.pre_sale?.fel_eligibility_status === 'not_eligible' ? <span className="text-amber-700">No elegible{entry.pre_sale.fel_eligibility_reason ? `: ${entry.pre_sale.fel_eligibility_reason}` : ''}</span> : 'Elegible'}</td></tr>)}</tbody></table></div></div></AuthenticatedLayout>;
}

function paymentMethodLabel(method?: string | null) {
    return ({ cash: 'Efectivo', card: 'Tarjeta', transfer: 'Transferencia', check: 'Cheque' } as Record<string, string>)[method ?? ''] ?? 'Sin definir';
}

function felLabel(status?: string | null) {
    return ({ not_requested: 'Pendiente de solicitar', pending: 'En proceso', failed: 'Fallida', unknown: 'Requiere conciliación', certified: 'Certificada' } as Record<string, string>)[status ?? ''] ?? 'Pendiente manual';
}
