import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, router } from '@inertiajs/react';
import { FormEvent, useState } from 'react';

type Pending = { case_id: number | null; sale_id: number; origin: 'external_reconciliation' | 'in_app_stop'; delivered_at?: string | null; amount: number; is_persisted: boolean; customer_name?: string | null; aging?: string };
type Paginated = { data: Pending[]; links: { url: string | null; label: string; active: boolean }[] };
type Filters = { origin?: string | null; aging?: string | null; assigned_to?: number | null; search?: string | null };
type Props = { pending_collections: Paginated; summary: { count: number; amount: number }; filters: Filters; users?: { id: number; name: string }[] };
const money = (amount: number) => 'Q ' + Number(amount || 0).toFixed(2);
const agingLabel: Record<string, string> = { today: 'Hoy', '1_3': '1–3 días', '4_7': '4–7 días', '8_plus': '8+ días' };

export default function Index({ pending_collections, summary, filters, users = [] }: Props) {
    const [search, setSearch] = useState(filters.search ?? '');
    const submit = (event: FormEvent) => { event.preventDefault(); router.get(route('routes.pending-collections.index'), { ...filters, search: search || undefined }, { preserveState: true, replace: true }); };
    const setFilter = (key: keyof Filters, value: string) => router.get(route('routes.pending-collections.index'), { ...filters, search: search || undefined, [key]: value || undefined }, { preserveState: true, replace: true });
    return <AuthenticatedLayout><Head title="Pendientes de cobro de rutas" /><main className="mx-auto max-w-6xl space-y-5 px-4 py-6 sm:px-6">
        <header><Link href={route('routes.delivery-batches.index')} className="text-sm font-semibold text-indigo-600">← Lotes de comprobantes</Link><h1 className="mt-2 text-2xl font-bold text-slate-950">Pendientes de cobro de rutas</h1><p className="mt-1 text-sm text-slate-600">Ventas entregadas pendientes de cobro operativo, no crédito contractual.</p></header>
        <section className="grid gap-3 sm:grid-cols-2"><Metric label="Ventas pendientes" value={String(summary.count)} /><Metric label="Importe pendiente" value={money(summary.amount)} /></section>
        <form onSubmit={submit} className="grid gap-3 rounded-xl border border-slate-200 bg-white p-4 sm:grid-cols-2 lg:grid-cols-5"><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Cliente o comprobante" className="rounded border-slate-300 text-sm" /><select value={filters.origin ?? ''} onChange={event => setFilter('origin', event.target.value)} className="rounded border-slate-300 text-sm"><option value="">Todos los orígenes</option><option value="external_reconciliation">Entrega externa</option><option value="in_app_stop">Entrega en Blunk</option></select><select value={filters.aging ?? ''} onChange={event => setFilter('aging', event.target.value)} className="rounded border-slate-300 text-sm"><option value="">Toda antigüedad</option>{Object.entries(agingLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select value={filters.assigned_to ?? ''} onChange={event => setFilter('assigned_to', event.target.value)} className="rounded border-slate-300 text-sm"><option value="">Todo responsable</option>{users.map(user => <option key={user.id} value={user.id}>{user.name}</option>)}</select><button className="rounded bg-indigo-600 px-3 py-2 text-sm font-semibold text-white">Buscar</button></form>
        <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">{pending_collections.data.length === 0 ? <p className="p-5 text-sm text-slate-500">No hay pendientes elegibles con estos filtros.</p> : <div className="divide-y">{pending_collections.data.map(row => <div key={row.origin + ':' + row.sale_id} className="flex items-center justify-between gap-4 p-4"><span><strong className="block">{row.customer_name || 'Cliente'} · Comprobante #{row.sale_id}</strong><span className="block text-sm text-slate-600">{row.origin === 'external_reconciliation' ? 'Entrega externa' : 'Entrega en Blunk'} · {row.delivered_at ? new Date(row.delivered_at).toLocaleString() : 'Sin fecha'} · {agingLabel[row.aging || 'today']}</span><span className="block text-xs text-slate-500">{row.is_persisted ? 'Seguimiento abierto' : 'Histórico derivado: se materializa sólo al registrar una acción.'}</span></span><span className="text-right"><strong className="block">{money(row.amount)}</strong><Link href={row.case_id ? route('routes.pending-collections.show', row.case_id) : route('routes.pending-collections.sales.show', row.sale_id)} className="mt-2 inline-block text-sm font-semibold text-indigo-600">Ver</Link></span></div>)}</div>}</section>
        <nav className="flex flex-wrap gap-1">{pending_collections.links.map((link, index) => <Link key={index} href={link.url || '#'} preserveScroll className={'rounded px-2 py-1 text-sm ' + (link.active ? 'bg-indigo-600 text-white' : 'border text-slate-600')}>{link.label.replace('&laquo;', '«').replace('&raquo;', '»')}</Link>)}</nav>
    </main></AuthenticatedLayout>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-xl font-bold">{value}</p></div>; }
