import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, router } from '@inertiajs/react';
import { FormEvent, useState } from 'react';

type User = { id: number; name: string };
type Event = { id: number; type: string; note?: string | null; occurred_at: string };
type PendingCase = { id?: number; sale_id: number; next_follow_up_at?: string | null; assigned_to?: User | null; sale?: { total: number; payment_status: string; customer?: { name?: string } | null } | null; events: Event[] };
type ReversibleCollection = { id: number; amount: number; payment_method: string; custody_status: string; cash_movement_id?: number | null; status: string; cash_session?: { id: number; status: string } | null };
type Props = { case: PendingCase | null; candidate: PendingCase | null; users: User[]; can_manage: boolean; can_collect: boolean; can_override: boolean; can_reverse: boolean; resolution_collection: ReversibleCollection | null; cash_policy: string; open_cash_session: { id: number } | null };
const key = () => crypto.randomUUID();

export default function Show({ case: persisted, candidate, users, can_manage, can_collect, can_override, can_reverse, resolution_collection, cash_policy, open_cash_session }: Props) {
    const pending = persisted || candidate!; const isDerived = !persisted;
    const [type, setType] = useState('note'); const [note, setNote] = useState(''); const [method, setMethod] = useState('transfer'); const [assignment, setAssignment] = useState(String(pending.assigned_to?.id ?? '')); const [next, setNext] = useState(pending.next_follow_up_at?.slice(0, 16) ?? ''); const [receiveCash, setReceiveCash] = useState(false); const [collector, setCollector] = useState(''); const [collectedAt, setCollectedAt] = useState(''); const [overrideReason, setOverrideReason] = useState(''); const [reversalReason, setReversalReason] = useState('payment_recorded_by_mistake'); const [reversalExplanation, setReversalExplanation] = useState(''); const [reverseConfirmed, setReverseConfirmed] = useState(false); const [cashAdjustmentConfirmed, setCashAdjustmentConfirmed] = useState(false);
    function event(e: FormEvent) { e.preventDefault(); router.post(isDerived ? route('routes.pending-collections.sales.events.store', pending.sale_id) : route('routes.pending-collections.events.store', pending.id), { idempotency_key: key(), type, note: note || null, occurred_at: new Date().toISOString() }); }
    function assign(e: FormEvent) { e.preventDefault(); if (!pending.id) return; router.patch(route('routes.pending-collections.assignment.update', pending.id), { idempotency_key: key(), assigned_to: assignment ? Number(assignment) : null, next_follow_up_at: next || null }); }
    function collect(e: FormEvent) { e.preventDefault(); router.post(isDerived ? route('routes.pending-collections.sales.collect', pending.sale_id) : route('routes.pending-collections.collect', pending.id), { idempotency_key: key(), amount: pending.sale?.total, payment_method: method, collected_by: collector ? Number(collector) : undefined, collected_at: collectedAt || undefined, override_reason: overrideReason || undefined, receive_cash_in_current_session: method === 'cash' && receiveCash }); }
    function reverse(e: FormEvent) { e.preventDefault(); if (!resolution_collection) return; router.post(route('routes.delivery-collections.reverse', resolution_collection.id), { idempotency_key: key(), reason_code: reversalReason, explanation: reversalExplanation, confirmed: reverseConfirmed, confirm_cash_adjustment: cashAdjustmentConfirmed }); }
    return <AuthenticatedLayout><Head title={'Pendiente #' + pending.id} /><main className="mx-auto max-w-3xl space-y-5 px-4 py-6 sm:px-6"><Link href={route('routes.pending-collections.index')} className="text-sm font-semibold text-indigo-600">← Pendientes de cobro</Link><header><h1 className="text-2xl font-bold">Pendiente de cobro de ruta</h1><p className="mt-1 text-sm text-slate-600">Comprobante #{pending.sale_id} · {pending.sale?.customer?.name || 'Cliente'}</p></header>
        <section className="rounded-xl border border-slate-200 bg-white p-4"><p><strong>Total:</strong> Q {Number(pending.sale?.total || 0).toFixed(2)}</p><p><strong>Estado financiero:</strong> {pending.sale?.payment_status}</p><p><strong>Próxima acción:</strong> {pending.next_follow_up_at ? new Date(pending.next_follow_up_at).toLocaleString() : 'Sin fecha'}</p></section>
        {can_manage && <section className="grid gap-4 md:grid-cols-2"><form onSubmit={event} className="rounded-xl border bg-white p-4"><h2 className="font-semibold">Registrar seguimiento</h2><select value={type} onChange={e => setType(e.target.value)} className="mt-3 w-full rounded border-slate-300">{['note','contact','visit','promise','no_response','dispute'].map(value => <option key={value}>{value}</option>)}</select><textarea value={note} onChange={e => setNote(e.target.value)} className="mt-3 w-full rounded border-slate-300" rows={3} /><button className="mt-3 rounded bg-indigo-600 px-3 py-2 text-sm font-semibold text-white">Guardar seguimiento</button></form>{!isDerived && <form onSubmit={assign} className="rounded-xl border bg-white p-4"><h2 className="font-semibold">Responsable y próxima acción</h2><select value={assignment} onChange={e => setAssignment(e.target.value)} className="mt-3 w-full rounded border-slate-300"><option value="">Sin asignar</option>{users.map(user => <option key={user.id} value={user.id}>{user.name}</option>)}</select><input type="datetime-local" value={next} onChange={e => setNext(e.target.value)} className="mt-3 w-full rounded border-slate-300" /><button className="mt-3 rounded border border-indigo-600 px-3 py-2 text-sm font-semibold text-indigo-700">Actualizar</button></form>}</section>}
        {can_collect && <form onSubmit={collect} className="rounded-xl border border-emerald-300 bg-emerald-50 p-4"><h2 className="font-semibold">Registrar cobro completo</h2><select value={method} onChange={e => { setMethod(e.target.value); setReceiveCash(false); }} className="mt-3 w-full rounded border-slate-300">{['cash','card','transfer','check'].map(value => <option key={value}>{value}</option>)}</select>{method === 'cash' && <div className="mt-3 rounded border border-amber-200 bg-amber-50 p-3 text-sm"><label className="flex gap-2"><input type="checkbox" checked={receiveCash} disabled={cash_policy !== 'immediate_branch_register' || !open_cash_session} onChange={e => setReceiveCash(e.target.checked)} /><span>Este efectivo está siendo recibido físicamente ahora en la caja abierta actual.</span></label><p className="mt-2 text-amber-800">{cash_policy === 'immediate_branch_register' && open_cash_session ? `Se registrará en la sesión actual #${open_cash_session.id}.` : 'El efectivo quedará bajo custodia del cobrador y deberá liquidarse posteriormente.'}</p></div>}{can_override && <details className="mt-3"><summary className="cursor-pointer text-sm font-medium">Override auditado</summary><select value={collector} onChange={e => setCollector(e.target.value)} className="mt-2 w-full rounded border-slate-300"><option value="">Cobrador actual</option>{users.map(user => <option key={user.id} value={user.id}>{user.name}</option>)}</select><input type="datetime-local" value={collectedAt} onChange={e => setCollectedAt(e.target.value)} className="mt-2 w-full rounded border-slate-300" /><textarea value={overrideReason} onChange={e => setOverrideReason(e.target.value)} placeholder="Motivo obligatorio si cambia cobrador o fecha" className="mt-2 w-full rounded border-slate-300" rows={2} /></details>}<button className="mt-3 rounded bg-emerald-700 px-3 py-2 text-sm font-semibold text-white">Registrar cobro</button></form>}
        {can_reverse && resolution_collection?.status === 'captured' && <form onSubmit={reverse} className="rounded-xl border border-rose-300 bg-rose-50 p-4"><h2 className="font-semibold text-rose-900">Reversar cobro</h2><p className="mt-1 text-sm text-rose-800">Corrige un cobro registrado por error; no representa una devolución de dinero al cliente.</p><select value={reversalReason} onChange={e => setReversalReason(e.target.value)} className="mt-3 w-full rounded border-slate-300">{['payment_recorded_by_mistake','wrong_customer','duplicate_collection','wrong_amount','other'].map(value => <option key={value}>{value}</option>)}</select><textarea required value={reversalExplanation} onChange={e => setReversalExplanation(e.target.value)} placeholder="Explicación obligatoria" className="mt-2 w-full rounded border-slate-300" rows={2} /><label className="mt-2 flex gap-2 text-sm"><input required type="checkbox" checked={reverseConfirmed} onChange={e => setReverseConfirmed(e.target.checked)} />Confirmo la corrección administrativa.</label>{resolution_collection.payment_method === 'cash' && resolution_collection.custody_status === 'posted_to_branch_cash' && resolution_collection.cash_session?.status === 'open' && <label className="mt-2 flex gap-2 text-sm"><input required type="checkbox" checked={cashAdjustmentConfirmed} onChange={e => setCashAdjustmentConfirmed(e.target.checked)} />Confirmo el ajuste administrativo en esta misma sesión de caja aún abierta.</label>}{resolution_collection.payment_method === 'cash' && resolution_collection.custody_status === 'posted_to_branch_cash' && resolution_collection.cash_session?.status === 'closed' && <p className="mt-2 text-sm text-amber-800">La sesión original está cerrada: la reversa quedará sólo en el ledger y no alterará ninguna caja histórica.</p>}<button className="mt-3 rounded bg-rose-700 px-3 py-2 text-sm font-semibold text-white">Reversar cobro</button></form>}
        <section className="rounded-xl border bg-white p-4"><h2 className="font-semibold">Historial</h2>{pending.events.length === 0 ? <p className="mt-2 text-sm text-slate-500">Sin seguimientos registrados.</p> : <div className="mt-3 space-y-3">{pending.events.map(event => <div key={event.id} className="border-l-2 border-slate-200 pl-3"><strong className="text-sm">{event.type}</strong><p className="text-sm">{event.note}</p><span className="text-xs text-slate-500">{new Date(event.occurred_at).toLocaleString()}</span></div>)}</div>}</section>
    </main></AuthenticatedLayout>;
}
