import ConfirmDialog from '@/Components/ConfirmDialog';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, router } from '@inertiajs/react';
import { useState } from 'react';

type Stop = {
    id: number; run_id: number; status: string; completed_at?: string | null;
    customer_name?: string | null; customer_address?: string | null; customer_phone?: string | null;
    delivery_notes?: string | null; collection_responsibility: string;
    sale?: { number?: number | null; total: number; status: string; payment_status: string; payment_method?: string | null; fel_status?: string | null; items?: Array<{ product_name: string; quantity: number }> } | null;
    operation_return?: { status: string; reason: string; completed_at?: string | null } | null;
};
const reasons = [['customer_absent', 'Cliente ausente'], ['customer_rejected', 'Cliente rechazó'], ['address_issue', 'Problema de dirección'], ['business_closed', 'Negocio cerrado'], ['damaged_goods', 'Mercadería dañada'], ['other', 'Otro']];

export default function StopPage({ stop, current_user_id, can_execute, can_return }: { stop: Stop; current_user_id: number; can_execute: boolean; can_return: boolean }) {
    const [status, setStatus] = useState('delivered');
    const [reason, setReason] = useState('customer_absent');
    const [notes, setNotes] = useState('');
    const [collect, setCollect] = useState(false);
    const [method, setMethod] = useState('cash');
    const [reference, setReference] = useState('');
    const [cash, setCash] = useState(false);
    const [returnReason, setReturnReason] = useState('');
    const [returnNote, setReturnNote] = useState('');
    const [received, setReceived] = useState(false);
    const [confirmReturn, setConfirmReturn] = useState(false);
    const [returnProcessing, setReturnProcessing] = useState(false);
    const [returnOpen, setReturnOpen] = useState(false);
    const [returnKey] = useState(() => crypto.randomUUID());
    const payment = { amount: stop.sale?.total, payment_method: method, reference: reference || null, collected_by: current_user_id, collected_at: new Date().toISOString(), receive_cash_in_current_session: cash };
    const complete = () => router.post(route('routes.delivery-stops.complete', stop.id), { idempotency_key: crypto.randomUUID(), delivery_status: status, not_delivered_reason_code: status === 'not_delivered' ? reason : null, delivery_notes: notes || null, collected: collect, ...(collect ? payment : {}) });
    const capture = () => router.post(route('routes.delivery-stops.collect', stop.id), { idempotency_key: crypto.randomUUID(), ...payment });
    const registerReturn = () => {
        if (!received || !returnReason.trim() || returnProcessing) return;
        router.post(route('routes.delivery-stops.return', stop.id), { idempotency_key: returnKey, reason: returnReason.trim(), note: returnNote.trim() || null, goods_received: true }, {
            preserveScroll: true, onStart: () => setReturnProcessing(true), onFinish: () => { setReturnProcessing(false); setConfirmReturn(false); },
        });
    };
    const maps = stop.customer_address ? `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(stop.customer_address)}` : null;
    const fields = <><p className="mt-2 text-sm">Importe completo: <strong>Q {Number(stop.sale?.total ?? 0).toFixed(2)}</strong></p><select className="mt-2 w-full rounded border p-2" value={method} onChange={event => setMethod(event.target.value)}>{[['cash', 'Efectivo'], ['card', 'Tarjeta'], ['transfer', 'Transferencia'], ['check', 'Cheque']].map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><input className="mt-2 w-full rounded border p-2" placeholder="Referencia" value={reference} onChange={event => setReference(event.target.value)} />{method === 'cash' && <label className="mt-2 flex gap-2 text-sm"><input type="checkbox" checked={cash} onChange={event => setCash(event.target.checked)} />Confirmo que este efectivo está siendo recibido físicamente ahora en la caja abierta actual. Se registrará en esta sesión; no corresponde a una caja histórica.</label>}</>;
    return <AuthenticatedLayout><Head title="Detalle de entrega" /><main className="mx-auto max-w-lg space-y-4 px-4 py-5">
        <Link href={route('routes.delivery-runs.show', stop.run_id)} className="text-sm font-semibold text-indigo-600">← Jornada</Link>
        <section className="rounded-xl border bg-white p-4"><h1 className="text-2xl font-bold">{stop.customer_name || 'Cliente'}</h1><p className="mt-2">{stop.customer_address || 'Sin dirección registrada'}</p><div className="mt-3 flex gap-3 text-sm">{stop.customer_phone && <a className="font-semibold text-indigo-600" href={`tel:${stop.customer_phone}`}>Llamar</a>}{maps && <a className="font-semibold text-indigo-600" href={maps} target="_blank" rel="noreferrer">Abrir Maps</a>}</div></section>
        <section className="rounded-xl border bg-white p-4 text-sm space-y-2"><p>Comprobante: <strong>#{stop.sale?.number ?? '-'}</strong></p><p>Total: <strong>Q {Number(stop.sale?.total ?? 0).toFixed(2)}</strong></p><p>FEL: {stop.sale?.fel_status ?? 'Contextual'}</p><p>Financiero: {stop.operation_return ? 'Operación devuelta' : stop.sale?.payment_status === 'paid' ? 'Cobrado' : 'Pendiente de cobro'}</p><p>Método acordado: {stop.sale?.payment_method ?? 'Sin definir'}</p></section>
        {stop.status !== 'pending' && <section className="rounded-xl border bg-slate-50 p-4"><strong>{stop.status === 'delivered' ? 'ENTREGADO' : 'NO ENTREGADO'}</strong>{stop.completed_at && <p className="mt-1 text-sm">Registrado: {new Date(stop.completed_at).toLocaleString()}</p>}{stop.delivery_notes && <p className="mt-1 text-sm">Nota: {stop.delivery_notes}</p>}{stop.operation_return && <p className="mt-2 font-semibold text-rose-700">Entregada → Devuelta {stop.operation_return.completed_at ? new Date(stop.operation_return.completed_at).toLocaleString() : ''} → Venta anulada. Motivo: {stop.operation_return.reason}</p>}</section>}
        {can_execute && stop.status === 'pending' && <section className="space-y-3 rounded-xl border bg-white p-4"><div className="grid grid-cols-2 gap-2"><button onClick={() => setStatus('delivered')} className={`rounded-xl py-4 font-bold ${status === 'delivered' ? 'bg-emerald-600 text-white' : 'border'}`}>ENTREGADO</button><button onClick={() => setStatus('not_delivered')} className={`rounded-xl py-4 font-bold ${status === 'not_delivered' ? 'bg-amber-600 text-white' : 'border'}`}>NO ENTREGADO</button></div>{status === 'not_delivered' && <select className="w-full rounded border p-3" value={reason} onChange={event => setReason(event.target.value)}>{reasons.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>}<textarea className="w-full rounded border p-3" value={notes} onChange={event => setNotes(event.target.value)} placeholder={status === 'not_delivered' && reason === 'other' ? 'Nota obligatoria' : 'Nota opcional'} />{stop.collection_responsibility === 'delivery_agent' && stop.sale?.payment_status === 'unpaid' && <section className="rounded-xl border border-indigo-200 bg-indigo-50 p-3"><label className="font-semibold"><input type="checkbox" checked={collect} onChange={event => setCollect(event.target.checked)} /> COBRAR IMPORTE COMPLETO</label>{collect && fields}</section>}<button onClick={complete} className="w-full rounded-xl bg-indigo-600 py-4 font-bold text-white">GUARDAR RESULTADO</button></section>}
        {can_execute && stop.status !== 'pending' && !stop.operation_return && stop.sale?.status === 'completed' && stop.collection_responsibility === 'delivery_agent' && stop.sale?.payment_status === 'unpaid' && <section className="rounded-xl border border-indigo-200 bg-indigo-50 p-4"><h2 className="font-bold">COBRAR IMPORTE COMPLETO</h2>{fields}<button onClick={capture} className="mt-3 w-full rounded-xl bg-indigo-600 py-3 font-bold text-white">REGISTRAR COBRO</button></section>}
        {can_return && !stop.operation_return && (!returnOpen ? <button type="button" className="rounded border border-rose-300 px-3 py-2 text-sm font-semibold text-rose-700" onClick={() => setReturnOpen(true)}>Registrar devolución</button> : <section className="space-y-2 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm"><div className="flex items-center justify-between"><h2 className="font-bold">Registrar devolución</h2><button type="button" className="text-slate-600 underline" onClick={() => setReturnOpen(false)}>Cancelar</button></div><p>Cliente: {stop.customer_name || 'Cliente'} · Venta #{stop.sale?.number ?? '-'} · Q {Number(stop.sale?.total ?? 0).toFixed(2)}</p><p>Entrega original: {stop.completed_at ? new Date(stop.completed_at).toLocaleString() : '-'}</p><ul className="list-inside list-disc">{stop.sale?.items?.map((item, index) => <li key={index}>{item.product_name} · {item.quantity}</li>)}</ul><textarea className="w-full rounded border p-2" placeholder="Motivo obligatorio" value={returnReason} onChange={event => setReturnReason(event.target.value)} /><textarea className="w-full rounded border p-2" placeholder="Nota opcional" value={returnNote} onChange={event => setReturnNote(event.target.value)} /><label className="flex gap-2"><input type="checkbox" checked={received} onChange={event => setReceived(event.target.checked)} />Confirmo que todos los productos fueron recibidos físicamente de vuelta.</label><button type="button" disabled={!received || !returnReason.trim() || returnProcessing} className="rounded bg-rose-700 px-3 py-2 font-semibold text-white disabled:opacity-50" onClick={() => setConfirmReturn(true)}>Registrar devolución</button><ConfirmDialog open={confirmReturn} title="Confirmar devolución" message="Confirma que los productos fueron recibidos de vuelta. La venta se anulará y el inventario se restaurará." confirmLabel="Confirmar devolución" processing={returnProcessing} onCancel={() => setConfirmReturn(false)} onConfirm={registerReturn} /></section>)}
    </main></AuthenticatedLayout>;
}
